requirements.txt: bump cryptography version to 2.7
"./bootstrap" on latest master fails with:

ERROR: paramiko 2.6.0 has requirement cryptography>=2.5, but you'll have
cryptography 2.2.1 which is incompatible.

Signed-off-by: Nathan Cutler <ncutler@suse.com>